/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as SpoolsRouteImport } from './routes/spools'
import { Route as SpoolsIdRouteImport } from './routes/spools_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoolsRoute = SpoolsRouteImport.update({
  id: '/spools',
  path: '/spools',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoolsIdRoute = SpoolsIdRouteImport.update({
  id: '/spools_/$id',
  path: '/spools/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/jobs': typeof JobsRoute
  '/spools': typeof SpoolsRoute
  '/spools/$id': typeof SpoolsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/jobs': typeof JobsRoute
  '/spools': typeof SpoolsRoute
  '/spools/$id': typeof SpoolsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/jobs': typeof JobsRoute
  '/spools': typeof SpoolsRoute
  '/spools_/$id': typeof SpoolsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guide' | '/jobs' | '/spools' | '/spools/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guide' | '/jobs' | '/spools' | '/spools/$id'
  id: '__root__' | '/' | '/guide' | '/jobs' | '/spools' | '/spools_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRoute
  JobsRoute: typeof JobsRoute
  SpoolsRoute: typeof SpoolsRoute
  SpoolsIdRoute: typeof SpoolsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spools': {
      id: '/spools'
      path: '/spools'
      fullPath: '/spools'
      preLoaderRoute: typeof SpoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spools_/$id': {
      id: '/spools_/$id'
      path: '/spools/$id'
      fullPath: '/spools/$id'
      preLoaderRoute: typeof SpoolsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRoute,
  JobsRoute: JobsRoute,
  SpoolsRoute: SpoolsRoute,
  SpoolsIdRoute: SpoolsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
